#!/bin/sh
set -e

echo "Reading pbuilder /etc/pbuilderrc"
echo "DIST: ${DIST}"
echo "ARCH: ${ARCH}"
echo "COMPONENTS: ${COMPONENTS}"

UBUNTU_DISTS="trusty vivid wily xenial yakkety zesty artful bionic cosmic disco eoan focal"
DEBIAN_DISTS="sid wheezy jessie stretch buster"


if [ "x${DIST}" = "x" ] && [ "x${DISTRIBUTION}" != "x" ]; then
    echo "warning: DIST is not set, using DISTRIBUTION=${DISTRIBUTION}"
    DIST=$DISTRIBUTION
elif [ "x${DIST}" != "x" ] && [ "x${DISTRIBUTION}" = "x" ]; then
    echo "warning: DISTRIBUTION is not set, using DIST=${DIST}"
    DISTRIBUTION=$DIST
else
    DIST=bionic
    echo "warning: no distribution set -- using default: ${DIST}"
fi

for NAME in $UBUNTU_DISTS; do
    if [ "$DIST" == "$NAME" ]; then
        DIST_TYPE=ubuntu
    fi
done

for NAME in $DEBIAN_DISTS; do
    if [ "$DIST" == "$NAME" ]; then
        DIST_TYPE=debian
    fi
done

if [ "$ARCH" == "armel" ] || [ "$ARCH" == "armhf" ] || [ "$ARCH" == "arm64" ]; then
    DEBOOTSTRAP="qemu-debootstrap"
fi

if [ "$DIST_TYPE" == "ubuntu" ]; then
    echo "Identified Ubuntu Distribution"

    COMPONENTS="main restricted universe multiverse"
    MIRRORSITE=http://de.archive.ubuntu.com/ubuntu/
    if [ "$ARCH" == "armel" ] || [ "$ARCH" == "armhf" ] || [ "$ARCH" == "arm64" ]; then
        # The default mirror site only provides i386 and
        MIRRORSITE=http://ports.ubuntu.com/ubuntu-ports
    fi
    DEBOOTSTRAPOPTS=("${DEBOOTSTRAPOPTS[@]}" --components=main,restricted,universe,multiverse)
    EXTRA_PACKAGES+="ruby-all-dev,"

elif [ "$DIST_TYPE" == "debian" ]; then
    echo "Identified Debian Distribution"
    echo " -- you have to make sure that 'debian-archive-keyring' is installed"

    if [ "$DIST" != "wheezy" ]; then
	# Not available on wheezy
    	EXTRA_PACKAGES="ruby-all-dev,"
    fi

    MIRRORSITE=http://ftp.no.debian.org/debian/
    if [ "$DIST" != "sid" ]; then
        # as long as sid is testing
        OTHERMIRROR="$OTHERMIRROR | deb $MIRRORSITE $DIST-backports $COMPONENTS"
    fi

    # Update keyring
    for((i=0; i < ${#DEBOOTSTRAPOPTS[@]}; i++))
    do
        DEBOOTSTRAPOPTS[$i]=`echo ${DEBOOTSTRAPOPTS[$i]} | sed 's#keyring=[^ ]\+#keyring=/usr/share/keyrings/debian-archive-keyring.gpg#g'`
    done

    COMPONENTS="main contrib non-free"
    DEBOOTSTRAPOPTS=("${DEBOOTSTRAPOPTS[@]}" --components=main,contrib,nonfree)
fi
# Append additional packages here
# cmake required by quite some package, including qtbindings
# apt-utils, e.g., for running apt-ftparchive in the hook dir see https://wiki.debian.org/PbuilderTricks
EXTRA_PACKAGES+="apt,cmake,dh-autoreconf,libgl1-mesa-dev,libboost-dev,yard,gem2deb"
DEBOOTSTRAPOPTS+=("--include=$EXTRA_PACKAGES")
echo "DIST_TYPE: ${DIST_TYPE}"
echo "DEBOOTSTRAPOPTS: ${DEBOOTSTRAPOPTS[@]}"
echo "COMPONENTS: $COMPONENTS"

# Enable network in pbuilder, otherwise embedded bootstrap scripts will fail
USENETWORK=yes


###   ORIGINAL VERSION   #####

# this is your configuration file for pbuilder.
# the file in /usr/share/pbuilder/pbuilderrc is the default template.
# /etc/pbuilderrc is the one meant for overwriting defaults in
# the default template
#
# read pbuilderrc.5 document for notes on specific options.
#MIRRORSITE=http://de.archive.ubuntu.com/ubuntu/

